<h1> Exemples Numpy

In [1]:
import numpy as np
import time

<h3>Tri stable de numpy sur une colonne

In [2]:
a=np.array([[2.12,43.3,0,0,1,150.,358],[4.13,43.1,1,0,2,152,359],[3.14,43.25,1,0,3,152,358],
            [2.25,42.75,1,3,4,152,357],[2.37,43.25,2,5,5,153,359],[2.75,43.35,2,3,6,156,356],
            [2.85,43.55,2,3,7,156,356],[2.95,42.35,3,3,8,156,356],[3.15,44.35,3,7,9,156,356]])
print(a)

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  3.14  43.25   1.     0.     3.   152.   358.  ]
 [  2.25  42.75   1.     3.     4.   152.   357.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.95  42.35   3.     3.     8.   156.   356.  ]
 [  3.15  44.35   3.     7.     9.   156.   356.  ]]


In [3]:
b= np.array([[2,45,0,0,3,120,355]])
print(b)
b[0]=[  12 , 25  , 0  , 0   ,3 ,120 ,355]
print(b)

[[  2  45   0   0   3 120 355]]
[[ 12  25   0   0   3 120 355]]


In [4]:
b=a[:,0:2]
print(b)
TWS=a[:,2:3]
print(TWS)


[[ 2.12 43.3 ]
 [ 4.13 43.1 ]
 [ 3.14 43.25]
 [ 2.25 42.75]
 [ 2.37 43.25]
 [ 2.75 43.35]
 [ 2.85 43.55]
 [ 2.95 42.35]
 [ 3.15 44.35]]
[[0.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [3.]
 [3.]]


In [5]:
# fabrication d'un dictionnaire
print(a[:,3])
dico = dict(zip(a[:,4],a[:,3]))
print(dico)

[0. 0. 0. 3. 5. 3. 3. 3. 7.]
{1.0: 0.0, 2.0: 0.0, 3.0: 0.0, 4.0: 3.0, 5.0: 5.0, 6.0: 3.0, 7.0: 3.0, 8.0: 3.0, 9.0: 7.0}


In [6]:
# remontee du dictionnaire 
n=3     #n = nombre des isochrones
nb=9
route=[nb]
for i in range (n) :      
    nb=int(dico[nb])
    route.append(nb)
route.reverse()
print(route)
    


[0, 3, 7, 9]


In [7]:
# tri stable sur 5eme colonne
a = a[a[:,4].argsort(kind='mergesort')]
print (a)

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  3.14  43.25   1.     0.     3.   152.   358.  ]
 [  2.25  42.75   1.     3.     4.   152.   357.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.95  42.35   3.     3.     8.   156.   356.  ]
 [  3.15  44.35   3.     7.     9.   156.   356.  ]]


In [8]:
# Puis sur la 4eme (l'ordre est conservé sur la dernière qui avait déjà été triée)
a = a[a[:,5].argsort(kind='mergesort')]
print (a)
print(a.shape[0])

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  3.14  43.25   1.     0.     3.   152.   358.  ]
 [  2.25  42.75   1.     3.     4.   152.   357.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.95  42.35   3.     3.     8.   156.   356.  ]
 [  3.15  44.35   3.     7.     9.   156.   356.  ]]
9


<h3> Exemple : On veut conserver les distances les plus courtes

In [9]:
for i in range(a.shape[0] - 1, 0, -1):  # ecremage
        if (a[i][5]) == (a[i - 1][5]):
            a = np.delete(a, i, 0)
print(a)

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]]


In [10]:
def twa(cap, dvent):
    twa = 180 - abs(((360 - dvent + cap) % 360) - 180)
    return twa
print(a[:,5])
dvent=np.array([300,101,100,270])
TWA=twa(a[:,5],dvent )
print (TWA)

[150. 152. 153. 156.]
[150.  51.  53. 114.]


<h3>Renumerotation des points sur la colonne 3

In [11]:
nbpoints= a.shape[0]
print (nbpoints)
# on renumerote a partir de 3 
N=np.array(range(3,a.shape[0]+3,1))
print (N)
a[:,3]=N
print(a)

4
[3 4 5 6]
[[  2.12  43.3    0.     3.     1.   150.   358.  ]
 [  4.13  43.1    1.     4.     2.   152.   359.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     6.     6.   156.   356.  ]]


In [12]:
# obtention des deux dereniers points
print(a)
print()
print(a[-3:,0:2])

[[  2.12  43.3    0.     3.     1.   150.   358.  ]
 [  4.13  43.1    1.     4.     2.   152.   359.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     6.     6.   156.   356.  ]]

[[ 4.13 43.1 ]
 [ 2.37 43.25]
 [ 2.75 43.35]]


<h3> Extraction des xy pour un trace d'isochrone

In [13]:
# premiere et deuxieme colonne
tic= time.time()
X=a[:,0].reshape(-1,1)
Y=a[:,1].reshape(-1,1)
for i in range (100):
   
    points=np.concatenate((-a[:,1].reshape(-1,1),a[:,1].reshape(-1,1)),axis=1)

print (points)
tac=time.time()
#print ((tic-tac))
#permutation et changement de signe 
#on inverse l'ordre des colonnes
#print(np.fliplr(b))
TWD= np.array( [248.04021058, 247.60624382, 247.30197041, 247.04196064, 246.78548283,
 246.5296352,  246.27327227, 247.60624382, 247.30197041,])
TWD2=TWD.reshape(-1,1)
tab= np.concatenate((points,TWD.reshape(-1,1)),axis=1)
print(tab)

[[-43.3   43.3 ]
 [-43.1   43.1 ]
 [-43.25  43.25]
 [-43.35  43.35]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 9

<h3>Formation d'un dictionnaire de correspondances points / points mere par slicing

In [14]:
# slice des colonnes 2 et 3
dico=a[:,2:4]
print(dico)

[[0. 3.]
 [1. 4.]
 [2. 5.]
 [2. 6.]]


<h3> Remontee des numeros de points

In [15]:
dico=np.array([[1,3],[3,8],[3,9],[3,10],[8,11],[8,12],[9,13],[11,14],[11,15],[12,16],[12,17],[16,18]])
print(dico)
ptm=dico[:,0]
print(ptm)
pt=dico[:,1]
print (pt)


[[ 1  3]
 [ 3  8]
 [ 3  9]
 [ 3 10]
 [ 8 11]
 [ 8 12]
 [ 9 13]
 [11 14]
 [11 15]
 [12 16]
 [12 17]
 [16 18]]
[ 1  3  3  3  8  8  9 11 11 12 12 16]
[ 3  8  9 10 11 12 13 14 15 16 17 18]


In [16]:
d = dict(zip(pt,ptm))
print (d)
nf=18


{3: 1, 8: 3, 9: 3, 10: 3, 11: 8, 12: 8, 13: 9, 14: 11, 15: 11, 16: 12, 17: 12, 18: 16}


<h3> Maximum sur une colonne

In [17]:
#ligne des maximums
print(np.argmax(a,axis=0))
#d'ou valeur max sur la 4eme colonne (axis =0)
print ('Valeur maximum sur colonne 5')
print (a[np.argmax(a,0)[5],5])


[1 3 2 3 3 3 1]
Valeur maximum sur colonne 5
156.0


In [18]:
T_a =np.array([10,15,12,13,11,18,15,17])
print(T_a)
print(np.argmin(T_a,0))   # 0 pour axis=0
print(T_a[np.argmin(T_a,0)])

[10 15 12 13 11 18 15 17]
0
10


<h3>Decomposition complexes en coordonnees

In [19]:
a=np.array([2+5*1j,3+4*1j,7+8*1j])
print(a)


[2.+5.j 3.+4.j 7.+8.j]


In [20]:
X=a.real.reshape(-1,1)
Y=a.imag.reshape(-1,1)
points=np.concatenate((-Y,X),axis=1)
print(points)
print(points.tolist())

[[-5.  2.]
 [-4.  3.]
 [-8.  7.]]
[[-5.0, 2.0], [-4.0, 3.0], [-8.0, 7.0]]


In [21]:
# en une operation avec latitudes en premier 
points=np.concatenate((-a.imag.reshape(-1,1),a.real.reshape(-1,1)),axis=1).tolist()
print(points)

[[-5.0, 2.0], [-4.0, 3.0], [-8.0, 7.0]]


In [22]:
print(np.shape(a))


(3,)


In [23]:
X=a.real.reshape(-1,1)
Y=a.imag.reshape(-1,1)
points=np.concatenate((-Y,X),axis=1)
print(type(points))
print(np.shape(points))

<class 'numpy.ndarray'>
(3, 2)


In [24]:
print(X)

[[2.]
 [3.]
 [7.]]


In [25]:

points= np.array([[10,45],[12,44],[13,47]])
points= np.array([[10,45]])
print (points)

[[10 45]]


In [26]:
# transformation en points complexes

X=points[:,0]
print (X)
Y=points[:,1]
print(Y)


cplx=points[:,0]+points[:,1]*1j
print(cplx)

[10]
[45]
[10.+45.j]


In [27]:
#transformation complexe en points x y
points=np.concatenate((cplx.real.reshape(-1,1),cplx.imag.reshape(-1,1)),axis=1)
print (points)
print (points.shape[0])

[[10. 45.]]
1


In [28]:
a=np.array([[2,3,6,3,3,358],[4,6,7,5,5,359],[8,2,9,4,1,0],[2,8,3,3,2,1],[2,7,3,3,1,10]])
print(a)

[[  2   3   6   3   3 358]
 [  4   6   7   5   5 359]
 [  8   2   9   4   1   0]
 [  2   8   3   3   2   1]
 [  2   7   3   3   1  10]]


In [29]:
# garder les deux premieres colonnes
b= a[:,0:2]
print(b)

[[2 3]
 [4 6]
 [8 2]
 [2 8]
 [2 7]]


In [30]:
#colonne des x
x=a.T[0]

print(x)
y=a.T[1]
#y=a[:,1:2]
print(y)

[2 4 8 2 2]
[3 6 2 8 7]


In [31]:
# manoeuvre inverse attention il faut changer de nom
u=x.reshape((1,-1))

v=y.reshape((1, -1))

c=np.concatenate((u.T, v.T),axis=1)
print (c)

[[2 3]
 [4 6]
 [8 2]
 [2 8]
 [2 7]]


In [32]:
cplx= np.array([[-10 - 2 * 1j, -15 + 3 * 1j, 50 + 10 * 1j]])
points=np.concatenate((cplx.real.reshape(-1,1),cplx.imag.reshape(-1,1)),axis=1)
print (points)

[[-10.  -2.]
 [-15.   3.]
 [ 50.  10.]]


In [33]:
points=np.array([[-73.62,-40.46]])
print(points.shape)                

(1, 2)


In [34]:
points=np.array([[-73.62,-40.46]])
A=(-3.8858333333333333-47.652499999999996j)
print(points.shape) 

(1, 2)


In [35]:
def dist_cap4(points,A):
    ''' points est une  liste de points a 2 dimensions , a est un point complexe '''
    ''' on retourne un tableau des distances et des caps '''
    print(points.shape)
    D=points[:,0]+points[:,1]*1j   # on transforme les points en points complexes
    C = A - D
    return np.abs(C), (450 + np.angle(C, deg=True)) % 360



print(dist_cap4(points,A))

(1, 2)
(array([70.1041087]), array([84.11123935]))


In [36]:
import time
X=np.array([0.,1,2,3,4,5,6,7,8,9])
Y= np.array(range(10))
Z = np.ones(10)
W=(np.ones(10)*3)
V=(np.array(range(10))+15)



#print(X.shape)
#print(Y.shape)
#print(Z.shape)
#print(W.shape)
#print(V.shape)
tic =time.time()
for i in range (1000000):
    X1=X.reshape(-1,1)
    Y1=Y.reshape(-1,1)
    Z1=Z.reshape(-1,1)
    V1=V.reshape(-1,1)
    W1=W.reshape(-1,1)

total=np.concatenate((X1,Y1,Z1,W1,V1), axis=1)
tac=time.time()

print(total) 
print(tac-tic)

[[ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]]
1.4170424938201904


In [37]:
X=np.array([0.,1,2,3,4,5,6,7,8,9])
Y= np.array(range(10))
Z = np.ones(10)
W=(np.ones(10)*3)
V=(np.array(range(10))+15)

tic =time.time()
for i in range (1000000):
    total2 =np.ones((10,5))
    #print(total2)
    total2[:,0]=X
    total2[:,1]=Y
    total2[:,2]=Z
    total2[:,3]=W
    total2[:,4]=V
tac=time.time()
print (total2)
print(tac-tic)


[[ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]]
2.885636568069458


In [38]:
import time
X=np.array([0.,1,2,3,4,5,6,7,8,9])
Y= np.array(range(10))
Z = np.ones(10)
W=(np.ones(10)*3)
V=(np.array(range(10))+15)



#print(X.shape)
#print(Y.shape)
#print(Z.shape)
#print(W.shape)
#print(V.shape)
tic =time.time()
for i in range (1000000):
    #X1=X.reshape(-1,1)
    #Y1=Y.reshape(-1,1)
    #Z1=Z.reshape(-1,1)
    #V1=V.reshape(-1,1)
    #W1=W.reshape(-1,1)

    total=np.concatenate((X.reshape(-1,1),Y.reshape(-1,1),Z.reshape(-1,1),W.reshape(-1,1),V.reshape(-1,1)), axis=1)
tac=time.time()

print(total) 
print(tac-tic)

[[ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]]
2.8725717067718506


In [39]:
X=np.array([0.,1,2,3,4,5,6,7,8,9])
Y= np.array(range(10))
Z = np.ones(10)
W=(np.ones(10)*3)
V=(np.array(range(10))+15)

X1=X.reshape(-1,1)
Y1=Y.reshape(-1,1)
Z1=Z.reshape(-1,1)
V1=V.reshape(-1,1)
W1=W.reshape(-1,1)

complet1=np.concatenate((X1,Y1,Z1,W1,V1), axis=1)

print (total)
print()

complet=np.array([[0,0,0,0,0]])
for i in range (0,3,1):
    X=np.array([0.,1,2,3,4,5,6,7,8,9])+10*i
    Y= np.array(range(10))
    Z = np.ones(10)
    W=(np.ones(10)*3)
    V=(np.array(range(10))+15)

    X1=X.reshape(-1,1)
    Y1=Y.reshape(-1,1)
    Z1=Z.reshape(-1,1)
    V1=V.reshape(-1,1)
    W1=W.reshape(-1,1)

    total2=np.concatenate((X1,Y1,Z1,W1,V1), axis=1)
    complet=np.concatenate((complet,total2),axis=0)
   
    print()
print()

print (complet)



[[ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]]





[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]
 [10.  0.  1.  3. 15.]
 [11.  1.  1.  3. 16.]
 [12.  2.  1.  3. 17.]
 [13.  3.  1.  3. 18.]
 [14.  4.  1.  3. 19.]
 [15.  5.  1.  3. 20.]
 [16.  6.  1.  3. 21.]
 [17.  7.  1.  3. 22.]
 [18.  8.  1.  3. 23.]
 [19.  9.  1.  3. 24.]
 [20.  0.  1.  3. 15.]
 [21.  1.  1.  3. 16.]
 [22.  2.  1.  3. 17.]
 [23.  3.  1.  3. 18.]
 [24.  4.  1.  3. 19.]
 [25.  5.  1.  3. 20.]
 [26.  6.  1.  3. 21.]
 [27.  7.  1.  3. 22.]
 [28.  8.  1.  3. 23.]
 [29.  9.  1.  3. 24.]]


In [40]:
complet=np.delete(complet,0,0)
print (complet)

[[ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]
 [10.  0.  1.  3. 15.]
 [11.  1.  1.  3. 16.]
 [12.  2.  1.  3. 17.]
 [13.  3.  1.  3. 18.]
 [14.  4.  1.  3. 19.]
 [15.  5.  1.  3. 20.]
 [16.  6.  1.  3. 21.]
 [17.  7.  1.  3. 22.]
 [18.  8.  1.  3. 23.]
 [19.  9.  1.  3. 24.]
 [20.  0.  1.  3. 15.]
 [21.  1.  1.  3. 16.]
 [22.  2.  1.  3. 17.]
 [23.  3.  1.  3. 18.]
 [24.  4.  1.  3. 19.]
 [25.  5.  1.  3. 20.]
 [26.  6.  1.  3. 21.]
 [27.  7.  1.  3. 22.]
 [28.  8.  1.  3. 23.]
 [29.  9.  1.  3. 24.]]


<h3>Operation sur une colonne

In [41]:
print(total)

[[ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]]


In [42]:
print(total[:,0])

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [43]:
total[:,0]=np.around(total[:,0]*2.1,0)
print (total)

[[ 0.  0.  1.  3. 15.]
 [ 2.  1.  1.  3. 16.]
 [ 4.  2.  1.  3. 17.]
 [ 6.  3.  1.  3. 18.]
 [ 8.  4.  1.  3. 19.]
 [10.  5.  1.  3. 20.]
 [13.  6.  1.  3. 21.]
 [15.  7.  1.  3. 22.]
 [17.  8.  1.  3. 23.]
 [19.  9.  1.  3. 24.]]


<h3>Version avec tableau Points,tws,twd

In [44]:
a=np.array([[2.12,43.3,0,0,1,150.,358],[4.13,43.1,1,0,2,152,359],[3.14,43.25,1,0,3,152,358],
            [2.25,42.75,1,3,4,152,357],[2.37,43.25,2,5,5,153,359],[2.75,43.35,2,3,6,156,356],
            [2.85,43.55,2,3,7,156,356],[2.95,42.35,3,3,8,156,356],[3.15,44.35,3,7,9,156,356]])
print(a)

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  3.14  43.25   1.     0.     3.   152.   358.  ]
 [  2.25  42.75   1.     3.     4.   152.   357.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.95  42.35   3.     3.     8.   156.   356.  ]
 [  3.15  44.35   3.     7.     9.   156.   356.  ]]


In [45]:
iso=a[:,0:3]
print (iso)

[[ 2.12 43.3   0.  ]
 [ 4.13 43.1   1.  ]
 [ 3.14 43.25  1.  ]
 [ 2.25 42.75  1.  ]
 [ 2.37 43.25  2.  ]
 [ 2.75 43.35  2.  ]
 [ 2.85 43.55  2.  ]
 [ 2.95 42.35  3.  ]
 [ 3.15 44.35  3.  ]]


In [46]:
polyline=np.split(iso[:,0:2],np.where(np.diff(iso[1:,2])==1)[0]+2)
print (polyline)
#print (polyline.tolist())

[array([[ 2.12, 43.3 ],
       [ 4.13, 43.1 ],
       [ 3.14, 43.25],
       [ 2.25, 42.75]]), array([[ 2.37, 43.25],
       [ 2.75, 43.35],
       [ 2.85, 43.55]]), array([[ 2.95, 42.35],
       [ 3.15, 44.35]])]


In [47]:
l2=[arr.tolist() for arr in polyline]
print(l2)

[[[2.12, 43.3], [4.13, 43.1], [3.14, 43.25], [2.25, 42.75]], [[2.37, 43.25], [2.75, 43.35], [2.85, 43.55]], [[2.95, 42.35], [3.15, 44.35]]]


<h3> Permutation et changement de signe sur les 2 premieres colonnes

In [48]:
a=np.array([[2.12,43.3,0,0,1,150.,358],[4.13,43.1,1,0,2,152,359],[3.14,43.25,1,0,3,152,358],
            [2.25,42.75,1,3,4,152,357],[2.37,43.25,2,5,5,153,359],[2.75,43.35,2,3,6,156,356],
            [2.85,43.55,2,3,7,156,356],[2.95,42.35,3,3,8,156,356],[3.15,44.35,3,7,9,156,356]])

points=a[:,0:3]
X=points[:,0].reshape(-1,1)
Y=points[:,1].reshape(-1,1)
N=points[:,2].reshape(-1,1)

tableau=np.concatenate((-Y,X,N),1)
print(points)
print(tableau)
points3=tableau[:,0:2]
print(points3)


[[ 2.12 43.3   0.  ]
 [ 4.13 43.1   1.  ]
 [ 3.14 43.25  1.  ]
 [ 2.25 42.75  1.  ]
 [ 2.37 43.25  2.  ]
 [ 2.75 43.35  2.  ]
 [ 2.85 43.55  2.  ]
 [ 2.95 42.35  3.  ]
 [ 3.15 44.35  3.  ]]
[[-43.3    2.12   0.  ]
 [-43.1    4.13   1.  ]
 [-43.25   3.14   1.  ]
 [-42.75   2.25   1.  ]
 [-43.25   2.37   2.  ]
 [-43.35   2.75   2.  ]
 [-43.55   2.85   2.  ]
 [-42.35   2.95   3.  ]
 [-44.35   3.15   3.  ]]
[[-43.3    2.12]
 [-43.1    4.13]
 [-43.25   3.14]
 [-42.75   2.25]
 [-43.25   2.37]
 [-43.35   2.75]
 [-43.55   2.85]
 [-42.35   2.95]
 [-44.35   3.15]]


In [49]:
points3[8]=[-55,3.15]

In [50]:
print(points3)

[[-43.3    2.12]
 [-43.1    4.13]
 [-43.25   3.14]
 [-42.75   2.25]
 [-43.25   2.37]
 [-43.35   2.75]
 [-43.55   2.85]
 [-42.35   2.95]
 [-55.     3.15]]


In [51]:
c= np.zeros((10,2))

In [52]:
print (c)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


<h3> Extraction une ligne sur cinq dans polyline

In [53]:
a=np.array([[2.12,43.3,0 ,0,1,150.,358],[4.13,43.1,1,0.,2,152,359],[1.75,43.25,1,0,3,152,358],
            [2.25,42.75,1,3,4,152,357],[2.37,43.25,2,5,5,153,359],[2.75,43.35,2,3,6,156,356],
            [2.85,43.55, 2 ,3,7,156,356],[2.95,42.35,3,3,8,156,356],[3.15,44.35,3,7,9,156,356],
            [2.12,43.3, 4 ,0,10,150.,358],[4.13,43.1,4,0,11,152,359],[3.14,43.25,5,0,12,152,358],
            [2.25,42.75, 5 ,3,13,152,357],[1.37,43.25, 5 ,5,14,153,359],[2.75,43.35, 5 ,3,15,156,356],
            [2.85,43.55, 7 ,3,16,156,356],[2.95,42.35,7,3,17,156,356],[3.15,44.35,7,7,18,156,356]
           
           ])
print(a)
polyline=np.split(a[:,0:2],np.where(np.diff(a[1:,2])==1)[0]+2)
print(polyline)
print()
l3=[arr.tolist() for arr in polyline]
print(l3)

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  1.75  43.25   1.     0.     3.   152.   358.  ]
 [  2.25  42.75   1.     3.     4.   152.   357.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.95  42.35   3.     3.     8.   156.   356.  ]
 [  3.15  44.35   3.     7.     9.   156.   356.  ]
 [  2.12  43.3    4.     0.    10.   150.   358.  ]
 [  4.13  43.1    4.     0.    11.   152.   359.  ]
 [  3.14  43.25   5.     0.    12.   152.   358.  ]
 [  2.25  42.75   5.     3.    13.   152.   357.  ]
 [  1.37  43.25   5.     5.    14.   153.   359.  ]
 [  2.75  43.35   5.     3.    15.   156.   356.  ]
 [  2.85  43.55   7.     3.    16.   156.   356.  ]
 [  2.95  42.35   7.     3.    17.   156.   356.  ]
 [  3.15  44.35   7.     7.    18.   156.   356.  ]]
[array([[ 2.12, 43.3 ],
       [ 4.13, 43.1 ],
       [ 1.75, 4

In [54]:
red=[]
black=[]
for i in range(len(l3)):
    if i%5==0:
        red.append(l3[i])
    else:
        black.append(l3[i])
        
print (red)
print (black)
               

[[[2.12, 43.3], [4.13, 43.1], [1.75, 43.25], [2.25, 42.75]]]
[[[2.37, 43.25], [2.75, 43.35], [2.85, 43.55]], [[2.95, 42.35], [3.15, 44.35]], [[2.12, 43.3], [4.13, 43.1]], [[3.14, 43.25], [2.25, 42.75], [1.37, 43.25], [2.75, 43.35], [2.85, 43.55], [2.95, 42.35], [3.15, 44.35]]]


<h3> Donner une valeur mini a une colonne



In [55]:
print (a)

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  1.75  43.25   1.     0.     3.   152.   358.  ]
 [  2.25  42.75   1.     3.     4.   152.   357.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.95  42.35   3.     3.     8.   156.   356.  ]
 [  3.15  44.35   3.     7.     9.   156.   356.  ]
 [  2.12  43.3    4.     0.    10.   150.   358.  ]
 [  4.13  43.1    4.     0.    11.   152.   359.  ]
 [  3.14  43.25   5.     0.    12.   152.   358.  ]
 [  2.25  42.75   5.     3.    13.   152.   357.  ]
 [  1.37  43.25   5.     5.    14.   153.   359.  ]
 [  2.75  43.35   5.     3.    15.   156.   356.  ]
 [  2.85  43.55   7.     3.    16.   156.   356.  ]
 [  2.95  42.35   7.     3.    17.   156.   356.  ]
 [  3.15  44.35   7.     7.    18.   156.   356.  ]]


In [56]:
b= a[:,0:1]
print(b)
b[b <2] = 2
print (b)


[[2.12]
 [4.13]
 [1.75]
 [2.25]
 [2.37]
 [2.75]
 [2.85]
 [2.95]
 [3.15]
 [2.12]
 [4.13]
 [3.14]
 [2.25]
 [1.37]
 [2.75]
 [2.85]
 [2.95]
 [3.15]]
[[2.12]
 [4.13]
 [2.  ]
 [2.25]
 [2.37]
 [2.75]
 [2.85]
 [2.95]
 [3.15]
 [2.12]
 [4.13]
 [3.14]
 [2.25]
 [2.  ]
 [2.75]
 [2.85]
 [2.95]
 [3.15]]


<h3>Extraction Gr lorsque l'on passe 360 Extraction du debut et de la fin du grib 

In [57]:
print(a)

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  2.    43.25   1.     0.     3.   152.   358.  ]
 [  2.25  42.75   1.     3.     4.   152.   357.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.95  42.35   3.     3.     8.   156.   356.  ]
 [  3.15  44.35   3.     7.     9.   156.   356.  ]
 [  2.12  43.3    4.     0.    10.   150.   358.  ]
 [  4.13  43.1    4.     0.    11.   152.   359.  ]
 [  3.14  43.25   5.     0.    12.   152.   358.  ]
 [  2.25  42.75   5.     3.    13.   152.   357.  ]
 [  2.    43.25   5.     5.    14.   153.   359.  ]
 [  2.75  43.35   5.     3.    15.   156.   356.  ]
 [  2.85  43.55   7.     3.    16.   156.   356.  ]
 [  2.95  42.35   7.     3.    17.   156.   356.  ]
 [  3.15  44.35   7.     7.    18.   156.   356.  ]]


In [58]:
i_ini=5
i_fin=2
fin=a.shape[1]-i_ini
debut=i_fin+1

print('fin : ',fin)
print('debut : ',debut)
print(a.shape[1])

if (i_fin<i_ini):
    b=a[:,-fin:]    # selection des 2 dernières colonnes
    c=a[:,:debut]  # selection des  
d=np.concatenate((b,c),axis=1)

print (b)  
print(c)
print(d)

fin :  2
debut :  3
7
[[150. 358.]
 [152. 359.]
 [152. 358.]
 [152. 357.]
 [153. 359.]
 [156. 356.]
 [156. 356.]
 [156. 356.]
 [156. 356.]
 [150. 358.]
 [152. 359.]
 [152. 358.]
 [152. 357.]
 [153. 359.]
 [156. 356.]
 [156. 356.]
 [156. 356.]
 [156. 356.]]
[[ 2.12 43.3   0.  ]
 [ 4.13 43.1   1.  ]
 [ 2.   43.25  1.  ]
 [ 2.25 42.75  1.  ]
 [ 2.37 43.25  2.  ]
 [ 2.75 43.35  2.  ]
 [ 2.85 43.55  2.  ]
 [ 2.95 42.35  3.  ]
 [ 3.15 44.35  3.  ]
 [ 2.12 43.3   4.  ]
 [ 4.13 43.1   4.  ]
 [ 3.14 43.25  5.  ]
 [ 2.25 42.75  5.  ]
 [ 2.   43.25  5.  ]
 [ 2.75 43.35  5.  ]
 [ 2.85 43.55  7.  ]
 [ 2.95 42.35  7.  ]
 [ 3.15 44.35  7.  ]]
[[150.   358.     2.12  43.3    0.  ]
 [152.   359.     4.13  43.1    1.  ]
 [152.   358.     2.    43.25   1.  ]
 [152.   357.     2.25  42.75   1.  ]
 [153.   359.     2.37  43.25   2.  ]
 [156.   356.     2.75  43.35   2.  ]
 [156.   356.     2.85  43.55   2.  ]
 [156.   356.     2.95  42.35   3.  ]
 [156.   356.     3.15  44.35   3.  ]
 [150.   358.     2.12

In [59]:
ngrib='384'
v1='18'
hutc=15
if (ngrib=='384' and v1=='18' and hutc <310) :  
    print('true')

true


In [60]:
GR = np.zeros((4,3,6))
print(GR)
print(GR.shape)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
(4, 3, 6)


In [61]:
PR=np.ones((2,3,6))
print (PR)
print(PR.shape)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
(2, 3, 6)


In [62]:
GR[1:3,:,:]=PR[:,:,:]
print (GR)


[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [63]:
#test de modulo



In [94]:
points= np.array([[170,50],[175,45],[190,35]])
print (points)


[[170  50]
 [175  45]
 [190  35]]


In [95]:
print(170%(-360))
print (190%(-360))

-190
-170


In [96]:
a=points[:,0:1]
print(a)

[[170]
 [175]
 [190]]


In [97]:
print (np.where(points[:,0:1]>180,-360+points[:,0:1],points[:,0:1]))

[[ 170]
 [ 175]
 [-170]]


In [98]:
points[:,0:1]=(np.where(points[:,0:1]>180,-360+points[:,0:1],points[:,0:1]))
print(points)

[[ 170   50]
 [ 175   45]
 [-170   35]]
