<h1> Exemples Numpy

In [2]:
import numpy as np

<h3>Tri stable de numpy sur une colonne

In [3]:
a=np.array([[2,3,6,3,3,358],[4,3,7,5,5,359],[4,3,9,4,1,0],[2,3,3,3,2,1],[2,3,3,3,1,10]])
print(a)

[[  2   3   6   3   3 358]
 [  4   3   7   5   5 359]
 [  4   3   9   4   1   0]
 [  2   3   3   3   2   1]
 [  2   3   3   3   1  10]]


In [4]:
# tri stable sur 5eme colonne
a = a[a[:,5].argsort(kind='mergesort')]
print (a)

[[  4   3   9   4   1   0]
 [  2   3   3   3   2   1]
 [  2   3   3   3   1  10]
 [  2   3   6   3   3 358]
 [  4   3   7   5   5 359]]


In [5]:
# Puis sur la premiere (l'ordre est conservé sur la dernière qui avait déjà été triée)
a = a[a[:,0].argsort(kind='mergesort')]
print (a)


[[  2   3   3   3   2   1]
 [  2   3   3   3   1  10]
 [  2   3   6   3   3 358]
 [  4   3   9   4   1   0]
 [  4   3   7   5   5 359]]


<h3> Maximum sur une colonne

In [6]:
#ligne des maximums
print(np.argmax(a,axis=0))
#d'ou valeur max sur la 4eme colonne (axis =0)
print ('Valeur maximum sur colonne 5')
print (a[np.argmax(a,0)[5],5])


[3 0 3 4 4 4]
Valeur maximum sur colonne 5
359


<h3>Decomposition complexes en coordonnees

In [7]:
a=np.array([2+5*1j,3+4*1j,7+8*1j])
print(a)

[2.+5.j 3.+4.j 7.+8.j]


In [8]:
X=a.real.reshape(-1,1)
Y=a.imag.reshape(-1,1)
points=np.concatenate((-Y,X),axis=1)
print(points)
print(points.tolist())

[[-5.  2.]
 [-4.  3.]
 [-8.  7.]]
[[-5.0, 2.0], [-4.0, 3.0], [-8.0, 7.0]]


In [9]:
# en une operation avec latitudes en premier 
points=np.concatenate((-a.imag.reshape(-1,1),a.real.reshape(-1,1)),axis=1).tolist()
print(points)

[[-5.0, 2.0], [-4.0, 3.0], [-8.0, 7.0]]


In [10]:
print(np.shape(a))


(3,)


In [13]:
X=a.real.reshape(-1,1)
Y=a.imag.reshape(-1,1)
points=np.concatenate((-Y,X),axis=1)
print(type(points))
print(np.shape(points))

<class 'numpy.ndarray'>
(3, 2)


In [14]:
print(X)

[[2.]
 [3.]
 [7.]]
