<h1> Exemples Numpy

In [38]:
import numpy as np
import time

<h3>Tri stable de numpy sur une colonne

In [67]:
a=np.array([[2.12,43.3,0,0,1,150.,358],[4.13,43.1,1,0,2,152,359],[3.14,43.25,1,0,3,152,358],
            [2.25,42.75,1,3,4,152,357],[2.37,43.25,2,5,5,153,359],[2.75,43.35,2,3,6,156,356],
            [2.85,43.55,2,3,7,156,356],[2.95,42.35,3,3,8,156,356],[3.15,44.35,3,7,9,156,356]])
print(a)

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  3.14  43.25   1.     0.     3.   152.   358.  ]
 [  2.25  42.75   1.     3.     4.   152.   357.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.95  42.35   3.     3.     8.   156.   356.  ]
 [  3.15  44.35   3.     7.     9.   156.   356.  ]]


In [79]:
b=a[:,0:2]
print(b)
TWS=a[:,2:3]
print(TWS)
print(d)

[[ 2.12 43.3 ]
 [ 4.13 43.1 ]
 [ 3.14 43.25]
 [ 2.25 42.75]
 [ 2.37 43.25]
 [ 2.75 43.35]
 [ 2.85 43.55]
 [ 2.95 42.35]
 [ 3.15 44.35]]
[[0.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [3.]
 [3.]]
[[0. 0.]
 [1. 0.]
 [1. 0.]
 [1. 3.]
 [2. 5.]
 [2. 3.]
 [2. 3.]
 [3. 3.]
 [3. 7.]]


In [72]:
# fabrication d'un dictionnaire
print(a[:,3])
dico = dict(zip(a[:,4],a[:,3]))
print(d)

[0. 0. 0. 3. 5. 3. 3. 3. 7.]
{1.0: 0.0, 2.0: 0.0, 3.0: 0.0, 4.0: 3.0, 5.0: 5.0, 6.0: 3.0, 7.0: 3.0, 8.0: 3.0, 9.0: 7.0}


In [74]:
# remontee du dictionnaire 
n=3     #n = nombre des isochrones
nb=9
route=[nb]
for i in range (n) :      
    nb=int(dico[nb])
    route.append(nb)
route.reverse()
print(route)
    


[0, 3, 7, 9]


In [61]:
# tri stable sur 5eme colonne
a = a[a[:,4].argsort(kind='mergesort')]
print (a)

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  3.14  43.25   1.     0.     3.   152.   358.  ]
 [  2.25  42.75   1.     3.     4.   152.   357.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.95  42.35   3.     3.     8.   156.   356.  ]
 [  3.15  44.35   3.     7.     9.   156.   356.  ]]


In [62]:
# Puis sur la 4eme (l'ordre est conservé sur la dernière qui avait déjà été triée)
a = a[a[:,5].argsort(kind='mergesort')]
print (a)
print(a.shape[0])

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  3.14  43.25   1.     0.     3.   152.   358.  ]
 [  2.25  42.75   1.     3.     4.   152.   357.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.95  42.35   3.     3.     8.   156.   356.  ]
 [  3.15  44.35   3.     7.     9.   156.   356.  ]]
9


<h3> On veut conserver les distances les plus courtes

In [63]:
for i in range(a.shape[0] - 1, 0, -1):  # ecremage
        if (a[i][5]) == (a[i - 1][5]):
            a = np.delete(a, i, 0)
print(a)

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]]


In [43]:
def twa(cap, dvent):
    twa = 180 - abs(((360 - dvent + cap) % 360) - 180)
    return twa
print(a[:,5])
dvent=np.array([300,101,100,270])
TWA=twa(a[:,5],dvent )
print (TWA)

[356. 357. 358. 359.]
[ 56. 104. 102.  89.]


<h3>Renumerotation des points sur la colonne 3

In [44]:
nbpoints= a.shape[0]
print (nbpoints)
# on renumerote a partir de 3 
N=np.array(range(3,a.shape[0]+3,1))
print (N)
a[:,3]=N
print(a)

4
[3 4 5 6]
[[  2.75  43.35   3.     3.   156.   356.  ]
 [  2.25  42.75   3.     4.   152.   357.  ]
 [  2.12  43.3    6.     5.   150.   358.  ]
 [  4.13  43.1    7.     6.   152.   359.  ]]


<h3> Extraction des xy pour un trace d'isochrone

In [85]:
# premiere et deuxieme colonne
tic= time.time()
X=a[:,0].reshape(-1,1)
Y=a[:,1].reshape(-1,1)
for i in range (100):
   
    points=np.concatenate((-a[:,1].reshape(-1,1),a[:,1].reshape(-1,1)),axis=1)

print (points)
tac=time.time()
#print ((tic-tac))
#permutation et changement de signe 
#on inverse l'ordre des colonnes
#print(np.fliplr(b))
TWD= np.array( [248.04021058, 247.60624382, 247.30197041, 247.04196064, 246.78548283,
 246.5296352,  246.27327227, 247.60624382, 247.30197041,])
TWD2=TWD.reshape(-1,1)
tab= np.concatenate((points,TWD.reshape(-1,1)),axis=1)
print(tab)

[[-43.3   43.3 ]
 [-43.1   43.1 ]
 [-43.25  43.25]
 [-42.75  42.75]
 [-43.25  43.25]
 [-43.35  43.35]
 [-43.55  43.55]
 [-42.35  42.35]
 [-44.35  44.35]]
[[-43.3         43.3        248.04021058]
 [-43.1         43.1        247.60624382]
 [-43.25        43.25       247.30197041]
 [-42.75        42.75       247.04196064]
 [-43.25        43.25       246.78548283]
 [-43.35        43.35       246.5296352 ]
 [-43.55        43.55       246.27327227]
 [-42.35        42.35       247.60624382]
 [-44.35        44.35       247.30197041]]


<h3>Formation d'un dictionnaire de correspondances points / points mere par slicing

In [173]:
# slice des colonnes 2 et 3
dico=a[:,2:4]
print(dico)

[[3. 3.]
 [3. 4.]
 [6. 5.]
 [7. 6.]]


<h3> Remontee des numeros de points

In [156]:
dico=np.array([[1,3],[3,8],[3,9],[3,10],[8,11],[8,12],[9,13],[11,14],[11,15],[12,16],[12,17],[16,18]])
print(dico)
ptm=dico[:,0]
print(ptm)
pt=dico[:,1]
print (pt)


[[ 1  3]
 [ 3  8]
 [ 3  9]
 [ 3 10]
 [ 8 11]
 [ 8 12]
 [ 9 13]
 [11 14]
 [11 15]
 [12 16]
 [12 17]
 [16 18]]
[ 1  3  3  3  8  8  9 11 11 12 12 16]
[ 3  8  9 10 11 12 13 14 15 16 17 18]


In [163]:
d = dict(zip(pt,ptm))
print (d)
nf=18


{3: 1, 8: 3, 9: 3, 10: 3, 11: 8, 12: 8, 13: 9, 14: 11, 15: 11, 16: 12, 17: 12, 18: 16}


<h3> Maximum sur une colonne

In [71]:
#ligne des maximums
print(np.argmax(a,axis=0))
#d'ou valeur max sur la 4eme colonne (axis =0)
print ('Valeur maximum sur colonne 5')
print (a[np.argmax(a,0)[5],5])


[3 0 3 4 4 4]
Valeur maximum sur colonne 5
359


In [187]:
T_a =np.array([10,15,12,13,11,18,15,17])
print(T_a)
print(np.argmin(T_a,0))   # 0 pour axis=0
print(T_a[np.argmin(T_a,0)])

[10 15 12 13 11 18 15 17]
0
10


<h3>Decomposition complexes en coordonnees

In [72]:
a=np.array([2+5*1j,3+4*1j,7+8*1j])
print(a)


[2.+5.j 3.+4.j 7.+8.j]


In [73]:
X=a.real.reshape(-1,1)
Y=a.imag.reshape(-1,1)
points=np.concatenate((-Y,X),axis=1)
print(points)
print(points.tolist())

[[-5.  2.]
 [-4.  3.]
 [-8.  7.]]
[[-5.0, 2.0], [-4.0, 3.0], [-8.0, 7.0]]


In [74]:
# en une operation avec latitudes en premier 
points=np.concatenate((-a.imag.reshape(-1,1),a.real.reshape(-1,1)),axis=1).tolist()
print(points)

[[-5.0, 2.0], [-4.0, 3.0], [-8.0, 7.0]]


In [75]:
print(np.shape(a))


(3,)


In [76]:
X=a.real.reshape(-1,1)
Y=a.imag.reshape(-1,1)
points=np.concatenate((-Y,X),axis=1)
print(type(points))
print(np.shape(points))

<class 'numpy.ndarray'>
(3, 2)


In [77]:
print(X)

[[2.]
 [3.]
 [7.]]


In [78]:

points= np.array([[10,45],[12,44],[13,47]])
points= np.array([[10,45]])
print (points)

[[10 45]]


In [79]:
# transformation en points complexes

X=points[:,0]
print (X)
Y=points[:,1]
print(Y)


cplx=points[:,0]+points[:,1]*1j
print(cplx)

[10]
[45]
[10.+45.j]


In [80]:
#transformation complexe en points x y
points=np.concatenate((cplx.real.reshape(-1,1),cplx.imag.reshape(-1,1)),axis=1)
print (points)
print (points.shape[0])

[[10. 45.]]
1


In [81]:
a=np.array([[2,3,6,3,3,358],[4,6,7,5,5,359],[8,2,9,4,1,0],[2,8,3,3,2,1],[2,7,3,3,1,10]])
print(a)

[[  2   3   6   3   3 358]
 [  4   6   7   5   5 359]
 [  8   2   9   4   1   0]
 [  2   8   3   3   2   1]
 [  2   7   3   3   1  10]]


In [82]:
# garder les deux premieres colonnes
b= a[:,0:2]
print(b)

[[2 3]
 [4 6]
 [8 2]
 [2 8]
 [2 7]]


In [83]:
#colonne des x
x=a.T[0]

print(x)
y=a.T[1]
#y=a[:,1:2]
print(y)

[2 4 8 2 2]
[3 6 2 8 7]


In [84]:
# manoeuvre inverse attention il faut changer de nom
u=x.reshape((1,-1))

v=y.reshape((1, -1))

c=np.concatenate((u.T, v.T),axis=1)
print (c)

[[2 3]
 [4 6]
 [8 2]
 [2 8]
 [2 7]]


In [85]:
cplx= np.array([[-10 - 2 * 1j, -15 + 3 * 1j, 50 + 10 * 1j]])
points=np.concatenate((cplx.real.reshape(-1,1),cplx.imag.reshape(-1,1)),axis=1)
print (points)

[[-10.  -2.]
 [-15.   3.]
 [ 50.  10.]]


In [86]:
points=np.array([[-73.62,-40.46]])
print(points.shape)                

(1, 2)


In [87]:
points=np.array([[-73.62,-40.46]])
A=(-3.8858333333333333-47.652499999999996j)
print(points.shape) 

(1, 2)


In [88]:
def dist_cap4(points,A):
    ''' points est une  liste de points a 2 dimensions , a est un point complexe '''
    ''' on retourne un tableau des distances et des caps '''
    print(points.shape)
    D=points[:,0]+points[:,1]*1j   # on transforme les points en points complexes
    C = A - D
    return np.abs(C), (450 + np.angle(C, deg=True)) % 360



print(dist_cap4(points,A))

(1, 2)
(array([70.1041087]), array([84.11123935]))


In [89]:
import time
X=np.array([0.,1,2,3,4,5,6,7,8,9])
Y= np.array(range(10))
Z = np.ones(10)
W=(np.ones(10)*3)
V=(np.array(range(10))+15)



#print(X.shape)
#print(Y.shape)
#print(Z.shape)
#print(W.shape)
#print(V.shape)
tic =time.time()
for i in range (1000000):
    X1=X.reshape(-1,1)
    Y1=Y.reshape(-1,1)
    Z1=Z.reshape(-1,1)
    V1=V.reshape(-1,1)
    W1=W.reshape(-1,1)

total=np.concatenate((X1,Y1,Z1,W1,V1), axis=1)
tac=time.time()

print(total) 
print(tac-tic)

[[ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]]
1.0499463081359863


In [90]:
X=np.array([0.,1,2,3,4,5,6,7,8,9])
Y= np.array(range(10))
Z = np.ones(10)
W=(np.ones(10)*3)
V=(np.array(range(10))+15)

tic =time.time()
for i in range (1000000):
    total2 =np.ones((10,5))
    #print(total2)
    total2[:,0]=X
    total2[:,1]=Y
    total2[:,2]=Z
    total2[:,3]=W
    total2[:,4]=V
tac=time.time()
print (total2)
print(tac-tic)


[[ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]]
2.655669689178467


In [91]:
import time
X=np.array([0.,1,2,3,4,5,6,7,8,9])
Y= np.array(range(10))
Z = np.ones(10)
W=(np.ones(10)*3)
V=(np.array(range(10))+15)



#print(X.shape)
#print(Y.shape)
#print(Z.shape)
#print(W.shape)
#print(V.shape)
tic =time.time()
for i in range (1000000):
    #X1=X.reshape(-1,1)
    #Y1=Y.reshape(-1,1)
    #Z1=Z.reshape(-1,1)
    #V1=V.reshape(-1,1)
    #W1=W.reshape(-1,1)

    total=np.concatenate((X.reshape(-1,1),Y.reshape(-1,1),Z.reshape(-1,1),W.reshape(-1,1),V.reshape(-1,1)), axis=1)
tac=time.time()

print(total) 
print(tac-tic)

[[ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]]
2.7774882316589355


In [92]:
X=np.array([0.,1,2,3,4,5,6,7,8,9])
Y= np.array(range(10))
Z = np.ones(10)
W=(np.ones(10)*3)
V=(np.array(range(10))+15)

X1=X.reshape(-1,1)
Y1=Y.reshape(-1,1)
Z1=Z.reshape(-1,1)
V1=V.reshape(-1,1)
W1=W.reshape(-1,1)

complet1=np.concatenate((X1,Y1,Z1,W1,V1), axis=1)

print (total)
print()

complet=np.array([[0,0,0,0,0]])
for i in range (0,3,1):
    X=np.array([0.,1,2,3,4,5,6,7,8,9])+10*i
    Y= np.array(range(10))
    Z = np.ones(10)
    W=(np.ones(10)*3)
    V=(np.array(range(10))+15)

    X1=X.reshape(-1,1)
    Y1=Y.reshape(-1,1)
    Z1=Z.reshape(-1,1)
    V1=V.reshape(-1,1)
    W1=W.reshape(-1,1)

    total2=np.concatenate((X1,Y1,Z1,W1,V1), axis=1)
    complet=np.concatenate((complet,total2),axis=0)
   
    print()
print()

print (complet)



[[ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]]





[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]
 [10.  0.  1.  3. 15.]
 [11.  1.  1.  3. 16.]
 [12.  2.  1.  3. 17.]
 [13.  3.  1.  3. 18.]
 [14.  4.  1.  3. 19.]
 [15.  5.  1.  3. 20.]
 [16.  6.  1.  3. 21.]
 [17.  7.  1.  3. 22.]
 [18.  8.  1.  3. 23.]
 [19.  9.  1.  3. 24.]
 [20.  0.  1.  3. 15.]
 [21.  1.  1.  3. 16.]
 [22.  2.  1.  3. 17.]
 [23.  3.  1.  3. 18.]
 [24.  4.  1.  3. 19.]
 [25.  5.  1.  3. 20.]
 [26.  6.  1.  3. 21.]
 [27.  7.  1.  3. 22.]
 [28.  8.  1.  3. 23.]
 [29.  9.  1.  3. 24.]]


In [93]:
complet=np.delete(complet,0,0)
print (complet)

[[ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]
 [10.  0.  1.  3. 15.]
 [11.  1.  1.  3. 16.]
 [12.  2.  1.  3. 17.]
 [13.  3.  1.  3. 18.]
 [14.  4.  1.  3. 19.]
 [15.  5.  1.  3. 20.]
 [16.  6.  1.  3. 21.]
 [17.  7.  1.  3. 22.]
 [18.  8.  1.  3. 23.]
 [19.  9.  1.  3. 24.]
 [20.  0.  1.  3. 15.]
 [21.  1.  1.  3. 16.]
 [22.  2.  1.  3. 17.]
 [23.  3.  1.  3. 18.]
 [24.  4.  1.  3. 19.]
 [25.  5.  1.  3. 20.]
 [26.  6.  1.  3. 21.]
 [27.  7.  1.  3. 22.]
 [28.  8.  1.  3. 23.]
 [29.  9.  1.  3. 24.]]


<h3>Operation sur une colonne

In [94]:
print(total)

[[ 0.  0.  1.  3. 15.]
 [ 1.  1.  1.  3. 16.]
 [ 2.  2.  1.  3. 17.]
 [ 3.  3.  1.  3. 18.]
 [ 4.  4.  1.  3. 19.]
 [ 5.  5.  1.  3. 20.]
 [ 6.  6.  1.  3. 21.]
 [ 7.  7.  1.  3. 22.]
 [ 8.  8.  1.  3. 23.]
 [ 9.  9.  1.  3. 24.]]


In [95]:
print(total[:,0])

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [96]:
total[:,0]=np.around(total[:,0]*2.1,0)
print (total)

[[ 0.  0.  1.  3. 15.]
 [ 2.  1.  1.  3. 16.]
 [ 4.  2.  1.  3. 17.]
 [ 6.  3.  1.  3. 18.]
 [ 8.  4.  1.  3. 19.]
 [10.  5.  1.  3. 20.]
 [13.  6.  1.  3. 21.]
 [15.  7.  1.  3. 22.]
 [17.  8.  1.  3. 23.]
 [19.  9.  1.  3. 24.]]


In [ ]:
<h3>Version avec tableau Points,tws,twd

In [ ]:
a=np.array([[2.12,43.3,0,0,1,150.,358],[4.13,43.1,1,0,2,152,359],[3.14,43.25,1,0,3,152,358],
            [2.25,42.75,1,3,4,152,357],[2.37,43.25,2,5,5,153,359],[2.75,43.35,2,3,6,156,356],
            [2.85,43.55,2,3,7,156,356],[2.95,42.35,3,3,8,156,356],[3.15,44.35,3,7,9,156,356]])
print(a)