In [1]:
import numpy as np

<h3>Creation np.zeros et np.ones

In [6]:
a= np.zeros(5)
b= np.zeros((2,3))
c= np.ones(6)
print (a)
print()
print (b)
print(c)

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1. 1.]


<h3> Creation range

In [5]:
range = np.arange(10, 20, 2)
print(range)

[10 12 14 16 18]


<h3>Creation random

In [20]:
#5 valeurs entre 0 et 1
a=np.float32(np.random.random(5))
print('a:\n',a)
# 6 valeurs entre 0 et 10
b=np.float32(np.random.random(6))*10
print('b:\n',b)

c=np.random.randint(1,7,size=(2,8))
print('c: \n',c)




a:
 [0.5884651  0.6596684  0.5332062  0.23053302 0.3948693 ]
b:
 [6.1880856 4.7486753 4.701322  7.160745  2.8799102 3.8346221]
c: 
 [[2 3 1 4 6 2 2 5]
 [1 6 1 4 3 4 3 5]]


<h3>Blocage du random

In [12]:
np.random.seed(0)
c=np.random.randint(1,11,size=10) # 11 n'est pas inclus
print(c)
# tableau aleatoire de 1 et 0 probabilité 0.25 0.75
N=256
lattice=np.int32(np.random.choice([1,0],N*N,p=[0.25,0.75]).reshpae(N,N))

[ 6  1  4  4  8 10  4  6  3  5]


<h3>Assignation type pour gpuarrays

In [ ]:
pointsx0 = np.array([ 0,  -5.8244,  -5.8375,  -5.8508,  -5.8639 ],dtype   = 'float32')
xa=np.float32(0.)
test_a = np.float32([range(1,5)] * 4)
test_b = np.float32([range(14,10, -1)]*4 )