Exemples numpy 2

In [1]:
import numpy as np

<h3>Aplatissement pour passage sur GPU

In [61]:
a=np.array([[[2,3,6,8],[3,5,4,10],[4,7,8,1]],[[2,3,6,8],[3,5,4,10],[4,7,8,15]]])
print(a)
print ('shape',a.shape)
b= np.ravel(a)
print(b)
i=1
j=0
k=3
print ('Valeur de a',a[i,j,k])

print ('valeur de b',b[(3*4*i)+(4*j)+k])

[[[ 2  3  6  8]
  [ 3  5  4 10]
  [ 4  7  8  1]]

 [[ 2  3  6  8]
  [ 3  5  4 10]
  [ 4  7  8 15]]]
shape (2, 3, 4)
[ 2  3  6  8  3  5  4 10  4  7  8  1  2  3  6  8  3  5  4 10  4  7  8 15]
Valeur de a 8
valeur de b 8


In [2]:
a=np.array([[2.12,43.3,0,0,1,150.,358],[4.13,43.1,1,0,2,152,359],[3.14,43.25,1,0,3,152,358],
            [2.25,42.75,1,3,4,152,357],[2.37,43.25,2,5,5,153,359],[2.75,43.35,2,3,6,156,356],
            [2.85,43.55,2,3,7,156,356],[2.95,42.35,3,3,8,156,356],[3.15,44.35,3,7,9,156,356]])
print(a)

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  3.14  43.25   1.     0.     3.   152.   358.  ]
 [  2.25  42.75   1.     3.     4.   152.   357.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.95  42.35   3.     3.     8.   156.   356.  ]
 [  3.15  44.35   3.     7.     9.   156.   356.  ]]


<h3>Copie de la derniere colonne dans les deux dernieres


In [3]:
b=np.copy(a)
print (b)

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  3.14  43.25   1.     0.     3.   152.   358.  ]
 [  2.25  42.75   1.     3.     4.   152.   357.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.95  42.35   3.     3.     8.   156.   356.  ]
 [  3.15  44.35   3.     7.     9.   156.   356.  ]]


In [4]:
b[-2:,:]=b[-3,:]

print(b)
print()
print (b[-2:,:])

[[  2.12  43.3    0.     0.     1.   150.   358.  ]
 [  4.13  43.1    1.     0.     2.   152.   359.  ]
 [  3.14  43.25   1.     0.     3.   152.   358.  ]
 [  2.25  42.75   1.     3.     4.   152.   357.  ]
 [  2.37  43.25   2.     5.     5.   153.   359.  ]
 [  2.75  43.35   2.     3.     6.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]]

[[  2.85  43.55   2.     3.     7.   156.   356.  ]
 [  2.85  43.55   2.     3.     7.   156.   356.  ]]


In [5]:
print (a.shape)


(9, 7)


<h3>Suppression de la dernière colonne

In [6]:
# je veux supprimer la derniere colonne
a= a[:,:-1]
print(a)

print (a.shape)

[[  2.12  43.3    0.     0.     1.   150.  ]
 [  4.13  43.1    1.     0.     2.   152.  ]
 [  3.14  43.25   1.     0.     3.   152.  ]
 [  2.25  42.75   1.     3.     4.   152.  ]
 [  2.37  43.25   2.     5.     5.   153.  ]
 [  2.75  43.35   2.     3.     6.   156.  ]
 [  2.85  43.55   2.     3.     7.   156.  ]
 [  2.95  42.35   3.     3.     8.   156.  ]
 [  3.15  44.35   3.     7.     9.   156.  ]]
(9, 6)


<h3>Creation d'un tableau de points complexes aleatoires  pour test

In [7]:
a=np.random.rand(10)*360+np.random.rand(10)*90*1j

print(a)


[ 21.56402194+45.41473743j  12.84853135+55.39076943j
 141.2486141 +64.64302258j 353.07461148+63.96649492j
 269.03080942 +2.16395728j  38.10530598+70.25584841j
  63.81598818+55.78788167j 298.40947368+67.49880917j
 153.93353506+69.11030715j 151.2980697 +58.99439371j]


##### 

In [8]:
np.random.seed(0)
a=(np.random.rand(10)*360).reshape(-1,1)
b=((np.random.rand(10)*90)-45).reshape(-1,1)
print(a)
print(b)


[[197.57286141]
 [257.46817189]
 [216.99481539]
 [196.15794588]
 [152.51572776]
 [232.5218807 ]
 [157.53139605]
 [321.03828028]
 [346.91859378]
 [138.03894678]]
[[ 26.25525343]
 [  2.60054278]
 [  6.1240105 ]
 [ 38.30369745]
 [-38.60675476]
 [-37.15836303]
 [-43.18034423]
 [ 29.9357861 ]
 [ 25.03410759]
 [ 33.30109334]]


In [9]:
c= np.concatenate((a,b),axis=1)
print(c)

[[197.57286141  26.25525343]
 [257.46817189   2.60054278]
 [216.99481539   6.1240105 ]
 [196.15794588  38.30369745]
 [152.51572776 -38.60675476]
 [232.5218807  -37.15836303]
 [157.53139605 -43.18034423]
 [321.03828028  29.9357861 ]
 [346.91859378  25.03410759]
 [138.03894678  33.30109334]]


In [10]:
print(c.shape[0])

10


In [11]:
print (c[:,:1])

[[197.57286141]
 [257.46817189]
 [216.99481539]
 [196.15794588]
 [152.51572776]
 [232.5218807 ]
 [157.53139605]
 [321.03828028]
 [346.91859378]
 [138.03894678]]


In [12]:
print(c[:,1:]+45)

[[71.25525343]
 [47.60054278]
 [51.1240105 ]
 [83.30369745]
 [ 6.39324524]
 [ 7.84163697]
 [ 1.81965577]
 [74.9357861 ]
 [70.03410759]
 [78.30109334]]


In [13]:
ilati =  c.T[1] + 90
print(ilati)

[116.25525343  92.60054278  96.1240105  128.30369745  51.39324524
  52.84163697  46.81965577 119.9357861  115.03410759 123.30109334]


In [14]:
x=np.array([1,2,1]).reshape((-1,1))
y=np.array([2,2,1]).reshape((-1,1))
z=(np.concatenate((x,y),axis=1))
z=[arr.tolist() for arr in z]
print(z)

[[1, 2], [2, 2], [1, 1]]


In [15]:
print(z[0])

[1, 2]


In [16]:
print(a[z[0]])

[[257.46817189]
 [216.99481539]]


/home/jphe/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed